const data = [
    {
        id:1,
        name:'Ilhom',
        status:'Student',
        age:19
    },
    {
        id:2,
        name:'Islom',
        status:'Developer',
        age:24
    },
    {
        id:3,
        name:'Rustam',
        status:'Medik',
        age:20
    },
    {
        id:4,
        name:'Mirkomil',
        status:'Pupil',
        age:15
    },
    {
        id:5,
        name:'Sulton',
        status:'Photographer',
        age:21
    },
    {
        id:6,
        name:'Davron',
        status:'Aplicant',
        age:17
    },
]

export default data